export const CUSTOMER_LIST = 'CUSTOMER_LIST';
export const CUSTOMER_CREATE = 'CUSTOMER_CREATE';
export const CUSTOMER_UPDATE = 'CUSTOMER_UPDATE';
export const CUSTOMER_DESTROY = 'CUSTOMER_DESTROY';
export const CUSTOMER_SORT = 'CUSTOMER_SORT';
export const CUSTOMER_SEARCH = 'CUSTOMER_SEARCH';
export const CUSTOMER_PREPARE = 'CUSTOMER_PREPARE';