export const ActionTypes = {
    FETCH_WALLETS_LOADING: 'FETCH_WALLETS_LOADING',
    FETCH_WALLETS_SUCCESS: 'FETCH_WALLETS_SUCCESS',
    FETCH_WALLETS_FAILURE: 'FETCH_WALLETS_FAILURE',
    FETCH_WALLETS_UPDATE:  'FETCH_WALLETS_UPDATE',
};
